apiVersion: v1
kind: Service

metadata:
  name: blue-green-service
  labels:
    app: blue-green-demo
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
  selector:
    #app: blue
    app: green

